### ISSUE TITLE
HTTP Request 시 CORS 오류 발생

### ISSUE THREAD

**Issue by snowman95** [wogns1026/mtd#15]
### 에러내용
CORS 헤더 'Access-Control-Allow-Origin' 누락으로 인해 리소스를 가져올 수 없음

### 원인
CORS 요청에 대한 응답에 필수 Access-Control-Allow-Origin헤더 가 누락됨
해당 헤더는 리소스에 액세스할 수 있는지 여부를 결정하는 데 사용됨
 
### 해결책
[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)

### 콘솔
![image](https://user-images.githubusercontent.com/89284542/146501090-62394e3f-846b-40e5-ad3d-56e1812bc064.png)

### 네트워크
![image](https://user-images.githubusercontent.com/89284542/146501729-4fdf20c3-bc52-4766-bbc1-3549f81eb9a1.png)

![image](https://user-images.githubusercontent.com/89284542/146501761-8d29a73e-1293-4314-b7c3-23ad1dc7348a.png)

**Comment by wogns1026** [comment]
- 우선 CrossOrigin 어노테이션을 Controller에 선언해줌으로써 해결
- 추후 CorsFilter를 생성해서 Controller마다 선언할 필요 없도록 개선필요
